const path = require("path");

const apps = [
  {
    name: "thrive-admin",
    script: "pnpm",
    args: "--filter admin-web run start",
    cwd: __dirname,
    exec_mode: "fork",
    instances: 1,
    env: { NODE_ENV: "production" },
    env_production: { NODE_ENV: "production" },
    env_staging: { NODE_ENV: "staging" },
    env_dev: { NODE_ENV: "development" },
    error_file: path.join(__dirname, "logs", "thrive-admin-error.log"),
    out_file: path.join(__dirname, "logs", "thrive-admin-out.log"),
    log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    max_memory_restart: "1G",
    min_uptime: "10s",
    listen_timeout: 8000,
  },
  {
    name: "thrive-examiner",
    script: "pnpm",
    args: "--filter examiner-web run start",
    cwd: __dirname,
    exec_mode: "fork",
    instances: 1,
    env: { NODE_ENV: "production" },
    env_production: { NODE_ENV: "production" },
    env_staging: { NODE_ENV: "staging" },
    env_dev: { NODE_ENV: "development" },
    error_file: path.join(__dirname, "logs", "thrive-examiner-error.log"),
    out_file: path.join(__dirname, "logs", "thrive-examiner-out.log"),
    log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    max_memory_restart: "1G",
    min_uptime: "10s",
    listen_timeout: 8000,
  },
  {
    name: "thrive-organization",
    script: "pnpm",
    args: "--filter organization-web run start",
    cwd: __dirname,
    exec_mode: "fork",
    instances: 1,
    env: { NODE_ENV: "production" },
    env_production: { NODE_ENV: "production" },
    env_staging: { NODE_ENV: "staging" },
    env_dev: { NODE_ENV: "development" },
    error_file: path.join(__dirname, "logs", "thrive-organization-error.log"),
    out_file: path.join(__dirname, "logs", "thrive-organization-out.log"),
    log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    max_memory_restart: "1G",
    min_uptime: "10s",
    listen_timeout: 8000,
  },
];

module.exports = { apps };
