export const ENV = {
  // Server Configuration
  DATABASE_URL: process.env.DATABASE_URL,
  AWS_REGION: process.env.AWS_REGION,
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
  AWS_S3_BUCKET: process.env.AWS_S3_BUCKET_NAME,
  NEXT_PUBLIC_CDN_URL: process.env.NEXT_PUBLIC_CDN_URL,
  OAUTH_CLIENT_ID: process.env.OAUTH_CLIENT_ID,
  OAUTH_CLIENT_SECRET: process.env.OAUTH_CLIENT_SECRET,
  OAUTH_REFRESH_TOKEN: process.env.OAUTH_REFRESH_TOKEN,
  OAUTH_USERNAME: process.env.OAUTH_USERNAME,
  ADMIN_NOTIFICATION_EMAIL: process.env.ADMIN_NOTIFICATION_EMAIL,
  GOOGLE_PLACES_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_PLACES_API_KEY,
  JWT_OTP_SECRET: process.env.JWT_OTP_SECRET,
  JWT_OTP_SECRET_EXPIRY: process.env.JWT_OTP_SECRET_EXPIRY,
  JWT_SET_PASSWORD_SECRET: process.env.JWT_SET_PASSWORD_SECRET,
  JWT_SET_PASSWORD_SECRET_EXPIRY: process.env.JWT_SET_PASSWORD_SECRET_EXPIRY,
  JWT_FORGET_PASSWORD_SECRET: process.env.JWT_FORGET_PASSWORD_SECRET,
  JWT_FORGET_PASSWORD_EXPIRY: process.env.JWT_FORGET_PASSWORD_EXPIRY,
  JWT_EXAMINER_INFO_REQUEST_SECRET:
    process.env.JWT_EXAMINER_INFO_REQUEST_SECRET,
  JWT_EXAMINER_INFO_REQUEST_SECRET_EXPIRY:
    process.env.JWT_EXAMINER_INFO_REQUEST_SECRET_EXPIRY,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_CLAIMANT_AVAILABILITY_URL:
    process.env.NEXT_PUBLIC_CLAIMANT_AVAILABILITY_URL,
  JWT_CLAIMANT_APPROVE_SECRET: process.env.JWT_CLAIMANT_APPROVE_SECRET,
  DOCS_REFRESH_TOKEN: process.env.DOCS_REFRESH_TOKEN,
  GOOGLE_CONTRACT_FOLDER_ID: process.env.GOOGLE_CONTRACT_FOLDER_ID,
  GOOGLE_REPORT_TEMPLATE_ID: process.env.GOOGLE_REPORT_TEMPLATE_ID,
  EMAIL_REPLY_TO: process.env.EMAIL_REPLY_TO,
} as const;
