const env = {
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_CLAIMANT_AVAILABILITY_URL: process.env.NEXT_PUBLIC_CLAIMANT_AVAILABILITY_URL,
  NEXT_PUBLIC_CLAIMANT_BOOKING_CANCEL_URL: process.env.NEXT_PUBLIC_CLAIMANT_BOOKING_CANCEL_URL,

  DATABASE_URL: process.env.DATABASE_URL,
  DATABASE_SSL_REQUIRED: process.env.DATABASE_SSL_REQUIRED === 'true' ? true : false,

  OAUTH_USERNAME: process.env.OAUTH_USERNAME,
  OAUTH_CLIENT_ID: process.env.OAUTH_CLIENT_ID,
  OAUTH_CLIENT_SECRET: process.env.OAUTH_CLIENT_SECRET,
  OAUTH_REFRESH_TOKEN: process.env.OAUTH_REFRESH_TOKEN,

  AWS_REGION: process.env.AWS_S3_REGION,
  AWS_ACCESS_KEY_ID: process.env.AWS_S3_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_S3_SECRET_ACCESS_KEY,
  AWS_S3_BUCKET_NAME: process.env.AWS_S3_BUCKET_NAME,

  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
  NEXTAUTH_URL: process.env.NEXTAUTH_URL,

  NEXT_PUBLIC_CDN_URL: process.env.NEXT_PUBLIC_CDN_URL,

  JWT_OTP_TOKEN_SECRET: process.env.JWT_OTP_TOKEN_SECRET,
  JWT_OTP_TOKEN_EXPIRY: process.env.JWT_OTP_TOKEN_EXPIRY,

  JWT_PASSWORD_TOKEN_SECRET: process.env.JWT_PASSWORD_TOKEN_SECRET,
  JWT_PASSWORD_TOKEN_EXPIRY: process.env.JWT_PASSWORD_TOKEN_EXPIRY,

  JWT_CLAIMANT_APPROVE_TOKEN_SECRET: process.env.JWT_CLAIMANT_APPROVE_TOKEN_SECRET,
  JWT_CLAIMANT_APPROVE_TOKEN_EXPIRY: process.env.JWT_CLAIMANT_APPROVE_TOKEN_EXPIRY,

  JWT_ORGANIZATION_INFO_REQUEST_TOKEN_SECRET: process.env.JWT_ORGANIZATION_INFO_REQUEST_TOKEN_SECRET,
  JWT_ORGANIZATION_INFO_REQUEST_TOKEN_EXPIRY: process.env.JWT_ORGANIZATION_INFO_REQUEST_TOKEN_EXPIRY,

  NEXT_PUBLIC_GOOGLE_PLACES_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_PLACES_API_KEY,

  NODE_ENV: process.env.NODE_ENV,
};

export default Object.freeze(env);
