import { ExaminerData } from "../types/ExaminerData";

export const fakeExaminers: ExaminerData[] = [
  {
    id: "1",
    name: "Dr. Sarah Ahmed",
    specialties: ["Orthopedic Surgery"],
    phone: "(647) 555-1923",
    email: "s.ahmed@precisionmed.ca",
    province: "Ontario",
    mailingAddress: "125 Bay Street, Suite 600",
    licenseNumber: "CPSO #09234",
    provinceOfLicensure: "Ontario",
    licenseExpiryDate: "2025-12-31",
    cvUrl: "/files/cv-sarah-ahmed.pdf",
    medicalLicenseUrl: "/files/license-sarah-ahmed.pdf",
    languagesSpoken: ["English", "Urdu"],
    yearsOfIMEExperience: 12,
    experienceDetails:
      "Board-certified orthopedic surgeon with over 12 years of experience conducting IMEs across personal injury, workplace disability, and accident benefit cases.",
    insuranceProofUrl: "/files/insurance-sarah-ahmed.pdf",
    signedNdaUrl: "/files/nda-sarah-ahmed.pdf",
    status: "PENDING",
    createdAt: "2025-01-10T12:00:00Z",
    updatedAt: "2025-01-20T12:00:00Z",
  },
  {
    id: "2",
    name: "Dr. John Smith",
    specialties: ["Neurology"],
    phone: "(416) 555-6789",
    email: "j.smith@neuroeval.ca",
    province: "Ontario",
    mailingAddress: "200 King Street, Suite 1500",
    licenseNumber: "CPSO #10234",
    provinceOfLicensure: "Ontario",
    licenseExpiryDate: "2026-05-15",
    cvUrl: "/files/cv-john-smith.pdf",
    medicalLicenseUrl: "/files/license-john-smith.pdf",
    languagesSpoken: ["English"],
    yearsOfIMEExperience: 15,
    experienceDetails:
      "Neurologist with extensive experience in workplace injury and traumatic brain injury IMEs.",
    insuranceProofUrl: "/files/insurance-john-smith.pdf",
    signedNdaUrl: "/files/nda-john-smith.pdf",
    status: "PENDING",
    createdAt: "2025-01-12T12:00:00Z",
    updatedAt: "2025-01-22T12:00:00Z",
  },
  {
    id: "3",
    name: "Dr. Emily Chen",
    specialties: ["Psychiatry"],
    phone: "(905) 555-8765",
    email: "e.chen@mentalhealthime.ca",
    province: "British Columbia",
    mailingAddress: "88 Granville Street, Suite 210",
    licenseNumber: "CPSBC #33456",
    provinceOfLicensure: "British Columbia",
    licenseExpiryDate: "2027-08-31",
    cvUrl: "/files/cv-emily-chen.pdf",
    medicalLicenseUrl: "/files/license-emily-chen.pdf",
    languagesSpoken: ["English", "Mandarin"],
    yearsOfIMEExperience: 9,
    experienceDetails:
      "Psychiatrist specializing in independent psychiatric evaluations for disability and workplace claims.",
    insuranceProofUrl: "/files/insurance-emily-chen.pdf",
    signedNdaUrl: "/files/nda-emily-chen.pdf",
    status: "PENDING",
    createdAt: "2025-01-14T12:00:00Z",
    updatedAt: "2025-01-24T12:00:00Z",
  },
  {
    id: "4",
    name: "Dr. Ahmed Khan",
    specialties: ["Internal Medicine"],
    phone: "(587) 555-4433",
    email: "a.khan@imealberta.ca",
    province: "Alberta",
    mailingAddress: "300 Jasper Ave, Suite 900",
    licenseNumber: "CPSA #99876",
    provinceOfLicensure: "Alberta",
    licenseExpiryDate: "2026-11-20",
    cvUrl: "/files/cv-ahmed-khan.pdf",
    medicalLicenseUrl: "/files/license-ahmed-khan.pdf",
    languagesSpoken: ["English", "Urdu"],
    yearsOfIMEExperience: 10,
    experienceDetails:
      "Experienced internist with IME practice focusing on chronic disease disability cases.",
    insuranceProofUrl: "/files/insurance-ahmed-khan.pdf",
    signedNdaUrl: "/files/nda-ahmed-khan.pdf",
    status: "PENDING",
    createdAt: "2025-01-15T12:00:00Z",
    updatedAt: "2025-01-25T12:00:00Z",
  },
  {
    id: "5",
    name: "Dr. Laura Brown",
    specialties: ["Family Medicine"],
    phone: "(604) 555-1122",
    email: "l.brown@familyime.ca",
    province: "British Columbia",
    mailingAddress: "400 Robson St, Suite 300",
    licenseNumber: "CPSBC #55678",
    provinceOfLicensure: "British Columbia",
    licenseExpiryDate: "2028-03-12",
    cvUrl: "/files/cv-laura-brown.pdf",
    medicalLicenseUrl: "/files/license-laura-brown.pdf",
    languagesSpoken: ["English", "French"],
    yearsOfIMEExperience: 7,
    experienceDetails:
      "Family physician with a focus on musculoskeletal injury IMEs and occupational health evaluations.",
    insuranceProofUrl: "/files/insurance-laura-brown.pdf",
    signedNdaUrl: "/files/nda-laura-brown.pdf",
    status: "PENDING",
    createdAt: "2025-01-16T12:00:00Z",
    updatedAt: "2025-01-26T12:00:00Z",
  },
  {
    id: "6",
    name: "Dr. David Lee",
    specialties: ["Orthopedic Surgery"],
    phone: "(403) 555-3344",
    email: "d.lee@orthoime.ca",
    province: "Alberta",
    mailingAddress: "789 Main St, Suite 100",
    licenseNumber: "CPSA #77890",
    provinceOfLicensure: "Alberta",
    licenseExpiryDate: "2026-09-10",
    cvUrl: "/files/cv-david-lee.pdf",
    medicalLicenseUrl: "/files/license-david-lee.pdf",
    languagesSpoken: ["English", "Korean"],
    yearsOfIMEExperience: 14,
    experienceDetails:
      "Orthopedic surgeon specializing in spinal injuries and post-operative IME assessments.",
    insuranceProofUrl: "/files/insurance-david-lee.pdf",
    signedNdaUrl: "/files/nda-david-lee.pdf",
    status: "PENDING",
    createdAt: "2025-01-17T12:00:00Z",
    updatedAt: "2025-01-27T12:00:00Z",
  },
  {
    id: "7",
    name: "Dr. Sophia Patel",
    specialties: ["Rheumatology"],
    phone: "(416) 555-2233",
    email: "s.patel@rheumime.ca",
    province: "Ontario",
    mailingAddress: "55 Bloor St, Suite 700",
    licenseNumber: "CPSO #66789",
    provinceOfLicensure: "Ontario",
    licenseExpiryDate: "2027-01-01",
    cvUrl: "/files/cv-sophia-patel.pdf",
    medicalLicenseUrl: "/files/license-sophia-patel.pdf",
    languagesSpoken: ["English", "Gujarati", "Hindi"],
    yearsOfIMEExperience: 11,
    experienceDetails:
      "Rheumatologist with experience in disability assessments related to autoimmune and chronic pain conditions.",
    insuranceProofUrl: "/files/insurance-sophia-patel.pdf",
    signedNdaUrl: "/files/nda-sophia-patel.pdf",
    status: "PENDING",
    createdAt: "2025-01-18T12:00:00Z",
    updatedAt: "2025-01-28T12:00:00Z",
  },
  {
    id: "8",
    name: "Dr. Michael Green",
    specialties: ["Cardiology"],
    phone: "(905) 555-9988",
    email: "m.green@cardioime.ca",
    province: "Ontario",
    mailingAddress: "22 Yonge St, Suite 1200",
    licenseNumber: "CPSO #77891",
    provinceOfLicensure: "Ontario",
    licenseExpiryDate: "2026-06-18",
    cvUrl: "/files/cv-michael-green.pdf",
    medicalLicenseUrl: "/files/license-michael-green.pdf",
    languagesSpoken: ["English"],
    yearsOfIMEExperience: 13,
    experienceDetails:
      "Cardiologist performing independent evaluations for cardiac-related disability and insurance claims.",
    insuranceProofUrl: "/files/insurance-michael-green.pdf",
    signedNdaUrl: "/files/nda-michael-green.pdf",
    status: "PENDING",
    createdAt: "2025-01-19T12:00:00Z",
    updatedAt: "2025-01-29T12:00:00Z",
  },
  {
    id: "9",
    name: "Dr. Olivia White",
    specialties: ["Dermatology"],
    phone: "(647) 555-5566",
    email: "o.white@skinime.ca",
    province: "Ontario",
    mailingAddress: "12 Front St, Suite 800",
    licenseNumber: "CPSO #88901",
    provinceOfLicensure: "Ontario",
    licenseExpiryDate: "2029-12-31",
    cvUrl: "/files/cv-olivia-white.pdf",
    medicalLicenseUrl: "/files/license-olivia-white.pdf",
    languagesSpoken: ["English", "Spanish"],
    yearsOfIMEExperience: 6,
    experienceDetails:
      "Dermatologist specializing in occupational skin disease and scarring assessments.",
    insuranceProofUrl: "/files/insurance-olivia-white.pdf",
    signedNdaUrl: "/files/nda-olivia-white.pdf",
    status: "PENDING",
    createdAt: "2025-01-20T12:00:00Z",
    updatedAt: "2025-01-30T12:00:00Z",
  },
  {
    id: "10",
    name: "Dr. Daniel Thompson",
    specialties: ["Sports Medicine"],
    phone: "(416) 555-7788",
    email: "d.thompson@sportime.ca",
    province: "Ontario",
    mailingAddress: "300 University Ave, Suite 400",
    licenseNumber: "CPSO #90923",
    provinceOfLicensure: "Ontario",
    licenseExpiryDate: "2026-04-14",
    cvUrl: "/files/cv-daniel-thompson.pdf",
    medicalLicenseUrl: "/files/license-daniel-thompson.pdf",
    languagesSpoken: ["English", "French"],
    yearsOfIMEExperience: 8,
    experienceDetails:
      "Sports medicine physician conducting IMEs for musculoskeletal injuries, athletes, and rehabilitation cases.",
    insuranceProofUrl: "/files/insurance-daniel-thompson.pdf",
    signedNdaUrl: "/files/nda-daniel-thompson.pdf",
    status: "PENDING",
    createdAt: "2025-01-21T12:00:00Z",
    updatedAt: "2025-01-31T12:00:00Z",
  },
];
