export const medicalSpecialtyOptions = [
  { value: "anesthesiology", label: "Anesthesiology" },
  { value: "cardiology", label: "Cardiology" },
  { value: "dermatology", label: "Dermatology" },
  { value: "emergency-medicine", label: "Emergency Medicine" },
  { value: "endocrinology", label: "Endocrinology" },
  { value: "family-medicine", label: "Family Medicine" },
  { value: "gastroenterology", label: "Gastroenterology" },
  { value: "general-surgery", label: "General Surgery" },
  { value: "gynecology", label: "Gynecology" },
  { value: "hematology", label: "Hematology" },
  { value: "infectious-diseases", label: "Infectious Diseases" },
  { value: "internal-medicine", label: "Internal Medicine" },
  { value: "nephrology", label: "Nephrology" },
  { value: "neurology", label: "Neurology" },
  { value: "neurosurgery", label: "Neurosurgery" },
  { value: "obstetrics", label: "Obstetrics" },
  { value: "oncology", label: "Oncology" },
  { value: "ophthalmology", label: "Ophthalmology" },
  { value: "orthopedic-surgery", label: "Orthopedic Surgery" },
  { value: "otolaryngology", label: "Otolaryngology (ENT)" },
  { value: "pathology", label: "Pathology" },
  { value: "pediatrics", label: "Pediatrics" },
  { value: "plastic-surgery", label: "Plastic Surgery" },
  { value: "psychiatry", label: "Psychiatry" },
  { value: "pulmonology", label: "Pulmonology" },
  { value: "radiology", label: "Radiology" },
  { value: "rheumatology", label: "Rheumatology" },
  { value: "urology", label: "Urology" },
  { value: "vascular-surgery", label: "Vascular Surgery" },
  { value: "other", label: "Other" },
];
