export const daysOptions = [
  { value: "monday", label: "Monday" },
  { value: "tuesday", label: "Tuesday" },
  { value: "wednesday", label: "Wednesday" },
  { value: "thursday", label: "Thursday" },
  { value: "friday", label: "Friday" },
  { value: "saturday", label: "Saturday" },
  { value: "sunday", label: "Sunday" },
];

export const travelDistanceOptions = [
  { value: "up-to-25-km", label: "Up to 25 km" },
  { value: "up-to-50-km", label: "Up to 50 km" },
  { value: "up-to-75-km", label: "Up to 75 km" },
  { value: "up-to-100-km", label: "Up to 100 km" },
  { value: "up-to-150-km", label: "Up to 150 km" },
  { value: "up-to-200-km", label: "Up to 200 km" },
  { value: "unlimited", label: "Unlimited" },
];

export const regionOptions = [
  { value: "toronto", label: "Toronto" },
  { value: "ottawa", label: "Ottawa" },
  { value: "hamilton", label: "Hamilton" },
  { value: "london", label: "London" },
  { value: "kitchener", label: "Kitchener" },
  { value: "windsor", label: "Windsor" },
  { value: "kingston", label: "Kingston" },
  { value: "barrie", label: "Barrie" },
  { value: "thunder-bay", label: "Thunder Bay" },
  { value: "sudbury", label: "Sudbury" },
  { value: "sault-ste-marie", label: "Sault Ste. Marie" },
  { value: "north-bay", label: "North Bay" },
  { value: "timmins", label: "Timmins" },
  { value: "other", label: "Other" },
];

export const medicalSpecialtyOptions = [
  { value: "anesthesiology", label: "Anesthesiology" },
  { value: "cardiology", label: "Cardiology" },
  { value: "dermatology", label: "Dermatology" },
  { value: "emergency-medicine", label: "Emergency Medicine" },
  { value: "endocrinology", label: "Endocrinology" },
  { value: "family-medicine", label: "Family Medicine" },
  { value: "gastroenterology", label: "Gastroenterology" },
  { value: "general-surgery", label: "General Surgery" },
  { value: "gynecology", label: "Gynecology" },
  { value: "hematology", label: "Hematology" },
  { value: "infectious-diseases", label: "Infectious Diseases" },
  { value: "internal-medicine", label: "Internal Medicine" },
  { value: "nephrology", label: "Nephrology" },
  { value: "neurology", label: "Neurology" },
  { value: "neurosurgery", label: "Neurosurgery" },
  { value: "obstetrics", label: "Obstetrics" },
  { value: "oncology", label: "Oncology" },
  { value: "ophthalmology", label: "Ophthalmology" },
  { value: "orthopedic-surgery", label: "Orthopedic Surgery" },
  { value: "otolaryngology", label: "Otolaryngology (ENT)" },
  { value: "pathology", label: "Pathology" },
  { value: "pediatrics", label: "Pediatrics" },
  { value: "plastic-surgery", label: "Plastic Surgery" },
  { value: "psychiatry", label: "Psychiatry" },
  { value: "pulmonology", label: "Pulmonology" },
  { value: "radiology", label: "Radiology" },
  { value: "rheumatology", label: "Rheumatology" },
  { value: "urology", label: "Urology" },
  { value: "vascular-surgery", label: "Vascular Surgery" },
  { value: "other", label: "Other" },
];

export const provinceOptions = [
  { value: "Ontario", label: "Ontario" },
  { value: "British Columbia  ", label: "British Columbia" },
  { value: "Manitoba", label: "Manitoba" },
  { value: "New Brunswick", label: "New Brunswick" },
  { value: "Newfoundland and Labrador", label: "Newfoundland and Labrador" },
  { value: "Nova Scotia", label: "Nova Scotia" },
  { value: "Prince Edward Island", label: "Prince Edward Island" },
  { value: "Quebec", label: "Quebec" },
  { value: "Saskatchewan", label: "Saskatchewan" },
  { value: "Northwest Territories", label: "Northwest Territories" },
  { value: "Nunavut", label: "Nunavut" },
  { value: "Yukon", label: "Yukon" },
];

export const yearsOfExperienceOptions = [
  { value: "less-than-1", label: "Less than 1 Year" },
  { value: "1-2", label: "1-2 Years" },
  { value: "2-3", label: "2-3 Years" },
  { value: "more-than-3", label: "More than 3 Years" },
];
